blank_issues_enabled: false
contact_links:
  - name: shadPS4 Troubleshooting/Support
    url: https://discord.gg/bFJxfftGW6
    about: For support and technical issues, please come to our Discord server.
